# Generated by Django 5.1.3 on 2024-11-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_name',
            new_name='phone_number',
        ),
    ]
